import * as registries from "./benchmarkParserRegistries.mjs";

// Recorded historical inventories are independent of the current default registry.
it.each([
  [9, ["owl-xml", "rdf-xml", "turtle", "owl-functional", "owl-manchester"]],
  [
    10,
    [
      "owl-xml",
      "rdf-xml",
      "turtle",
      "owl-dl",
      "owl-functional",
      "owl-manchester",
    ],
  ],
  [
    11,
    [
      "owl-xml",
      "rdf-xml",
      "turtle",
      "owl-dl",
      "owl-krss2",
      "owl-functional",
      "owl-manchester",
    ],
  ],
  [
    12,
    [
      "owl-xml",
      "rdf-xml",
      "ntriples",
      "turtle",
      "owl-dl",
      "owl-krss2",
      "owl-functional",
      "owl-manchester",
    ],
  ],
  [
    13,
    [
      "owl-xml",
      "rdf-xml",
      "nquads",
      "ntriples",
      "turtle",
      "owl-dl",
      "owl-krss2",
      "owl-functional",
      "owl-manchester",
    ],
  ],
  [
    14,
    [
      "owl-xml",
      "rdf-xml",
      "nquads",
      "ntriples",
      "trig",
      "turtle",
      "owl-dl",
      "owl-krss2",
      "owl-functional",
      "owl-manchester",
    ],
  ],
  [
    15,
    [
      "owl-xml",
      "jsonld",
      "rdf-xml",
      "nquads",
      "ntriples",
      "trig",
      "turtle",
      "owl-dl",
      "owl-krss2",
      "owl-functional",
      "owl-manchester",
    ],
  ],
  [
    16,
    [
      "owl-xml",
      "jsonld",
      "rdf-xml",
      "nquads",
      "ntriples",
      "trig",
      "turtle",
      "owl-dl",
      "owl-krss2",
      "owl-functional",
      "owl-manchester",
    ],
  ],
  [
    17,
    [
      "owl-xml",
      "jsonld",
      "rdf-xml",
      "nquads",
      "ntriples",
      "trig",
      "turtle",
      "owl-dl",
      "owl-krss1",
      "owl-krss2",
      "owl-functional",
      "owl-manchester",
    ],
  ],
])("preserves phase %i order and membership", (phase, expected) => {
  const actual = registries[`phase${phase}Descriptors`];
  expect(actual.map((descriptor) => descriptor.id)).toEqual(expected);
  expect(Object.isFrozen(actual)).toBe(true);
});
