import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonGenerator;
import java.util.*;
import java.nio.file.Files;
import java.nio.file.Path;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.io.StringDocumentSource;
import org.semanticweb.owlapi.model.*;
import org.semanticweb.owlapi.profiles.*;

/** Independent public-API probes derived from W3C profile grammar productions. */
public final class RunRC2Profiles {
  public static void main(String[] arguments) throws Exception {
    Map<String,String> cases = new LinkedHashMap<>();
    cases.put("empty", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j))  )");
    cases.put("subNamed", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A :B) )");
    cases.put("subThing", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(owl:Thing :B) )");
    cases.put("superThing", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A owl:Thing) )");
    cases.put("subIntersection", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectIntersectionOf(:A :B) :A) )");
    cases.put("superIntersection", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectIntersectionOf(:A :B)) )");
    cases.put("subUnion", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectUnionOf(:A :B) :A) )");
    cases.put("superUnion", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectUnionOf(:A :B)) )");
    cases.put("subComplement", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectComplementOf(:A) :B) )");
    cases.put("superComplement", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectComplementOf(:B)) )");
    cases.put("superComplementComplex", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectComplementOf(ObjectUnionOf(:A :B))) )");
    cases.put("subSomeThing", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectSomeValuesFrom(:p owl:Thing) :A) )");
    cases.put("subSomeNamed", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectSomeValuesFrom(:p :B) :A) )");
    cases.put("superSomeNamed", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectSomeValuesFrom(:p :B)) )");
    cases.put("superSomeComplex", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectSomeValuesFrom(:p ObjectIntersectionOf(:A :B))) )");
    cases.put("subAll", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectAllValuesFrom(:p :B) :A) )");
    cases.put("superAll", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectAllValuesFrom(:p :B)) )");
    cases.put("superAllThing", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectAllValuesFrom(:p owl:Thing)) )");
    cases.put("subHasValue", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectHasValue(:p :i) :A) )");
    cases.put("superHasValue", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectHasValue(:p :i)) )");
    cases.put("subSelf", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectHasSelf(:p) :A) )");
    cases.put("superSelf", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectHasSelf(:p)) )");
    cases.put("subOneOf", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectOneOf(:i) :A) )");
    cases.put("superOneOf", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectOneOf(:i)) )");
    cases.put("manyOneOf", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectOneOf(:i :j) :A) )");
    cases.put("subMin0", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(ObjectMinCardinality(0 :p :B) :A) )");
    cases.put("superMin1", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectMinCardinality(1 :p :B)) )");
    cases.put("superMax0", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectMaxCardinality(0 :p :B)) )");
    cases.put("superMax1", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectMaxCardinality(1 :p owl:Thing)) )");
    cases.put("superMax2", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectMaxCardinality(2 :p :B)) )");
    cases.put("superExact1", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectExactCardinality(1 :p :B)) )");
    cases.put("subDataSome", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(DataSomeValuesFrom(:d xsd:string) :A) )");
    cases.put("superDataSome", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A DataSomeValuesFrom(:d xsd:string)) )");
    cases.put("subDataAll", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(DataAllValuesFrom(:d xsd:string) :A) )");
    cases.put("superDataAll", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A DataAllValuesFrom(:d xsd:string)) )");
    cases.put("subDataValue", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(DataHasValue(:d \"text\") :A) )");
    cases.put("superDataValue", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A DataHasValue(:d \"text\")) )");
    cases.put("superDataMin", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A DataMinCardinality(1 :d xsd:string)) )");
    cases.put("superDataMax1", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A DataMaxCardinality(1 :d xsd:string)) )");
    cases.put("superDataMax2", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A DataMaxCardinality(2 :d xsd:string)) )");
    cases.put("superDataExact", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A DataExactCardinality(1 :d xsd:string)) )");
    cases.put("dataIntersection", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyRange(:d DataIntersectionOf(xsd:string xsd:token)) )");
    cases.put("dataUnion", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyRange(:d DataUnionOf(xsd:string xsd:integer)) )");
    cases.put("dataComplement", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyRange(:d DataComplementOf(xsd:string)) )");
    cases.put("dataOneOf", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyRange(:d DataOneOf(\"text\")) )");
    cases.put("dataManyOneOf", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyRange(:d DataOneOf(\"text\" \"other\")) )");
    cases.put("dataRestriction", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyRange(:d DatatypeRestriction(xsd:integer xsd:minInclusive \"0\"^^xsd:integer)) )");
    cases.put("inverseUse", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(:A ObjectSomeValuesFrom(ObjectInverseOf(:p) :B)) )");
    cases.put("anonymousIndividual", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) ClassAssertion(:A _:i) )");
    cases.put("equivSome", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) EquivalentClasses(:A ObjectSomeValuesFrom(:p owl:Thing)) )");
    cases.put("equivValue", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) EquivalentClasses(:A ObjectHasValue(:p :i)) )");
    cases.put("equivIntersection", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) EquivalentClasses(:A ObjectIntersectionOf(:A :B)) )");
    cases.put("disjointSome", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DisjointClasses(:A ObjectSomeValuesFrom(:p owl:Thing)) )");
    cases.put("disjointUnion", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DisjointUnion(:A :A :B) )");
    cases.put("objectDomain", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) ObjectPropertyDomain(:p ObjectSomeValuesFrom(:q :A)) )");
    cases.put("objectRange", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) ObjectPropertyRange(:p ObjectAllValuesFrom(:q :A)) )");
    cases.put("dataDomain", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyDomain(:d ObjectSomeValuesFrom(:p :A)) )");
    cases.put("propertySub", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubObjectPropertyOf(:p :q) )");
    cases.put("propertyChain", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubObjectPropertyOf(ObjectPropertyChain(:p :q) :r) )");
    cases.put("propertyEquivalent", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) EquivalentObjectProperties(:p :q) )");
    cases.put("propertyDisjoint", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DisjointObjectProperties(:p :q) )");
    cases.put("propertyInverse", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) InverseObjectProperties(:p :q) )");
    cases.put("dataSub", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubDataPropertyOf(:d :e) )");
    cases.put("dataEquivalent", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) EquivalentDataProperties(:d :e) )");
    cases.put("dataDisjoint", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DisjointDataProperties(:d :e) )");
    cases.put("FunctionalObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) FunctionalObjectProperty(:p) )");
    cases.put("InverseFunctionalObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) InverseFunctionalObjectProperty(:p) )");
    cases.put("ReflexiveObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) ReflexiveObjectProperty(:p) )");
    cases.put("IrreflexiveObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) IrreflexiveObjectProperty(:p) )");
    cases.put("SymmetricObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SymmetricObjectProperty(:p) )");
    cases.put("AsymmetricObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) AsymmetricObjectProperty(:p) )");
    cases.put("TransitiveObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) TransitiveObjectProperty(:p) )");
    cases.put("functionalData", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) FunctionalDataProperty(:d) )");
    cases.put("key", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) HasKey(:A (:p) (:d)) )");
    cases.put("same", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SameIndividual(:i :j) )");
    cases.put("different", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DifferentIndividuals(:i :j) )");
    cases.put("classAssertion", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) ClassAssertion(:A :i) )");
    cases.put("complexClassAssertion", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) ClassAssertion(ObjectSomeValuesFrom(:p :A) :i) )");
    cases.put("objectAssertion", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) ObjectPropertyAssertion(:p :i :j) )");
    cases.put("dataAssertion", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyAssertion(:d :i \"text\") )");
    cases.put("negativeObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) NegativeObjectPropertyAssertion(:p :i :j) )");
    cases.put("negativeData", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) NegativeDataPropertyAssertion(:d :i \"text\") )");
    cases.put("annotation", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) AnnotationAssertion(rdfs:label :A \"label\") )");
    cases.put("annotationSub", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubAnnotationPropertyOf(rdfs:label rdfs:comment) )");
    cases.put("annotationDomain", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) AnnotationPropertyDomain(rdfs:label <urn:profiles:domain>) )");
    cases.put("annotationRange", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) AnnotationPropertyRange(rdfs:label <urn:profiles:range>) )");
    cases.put("datatypeDefinition", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(:DT)) DatatypeDefinition(:DT xsd:string) )");
    cases.put("chainRangeMissing", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubObjectPropertyOf(ObjectPropertyChain(:p :q) :r) ObjectPropertyRange(:r :A) )");
    cases.put("chainRangePresent", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubObjectPropertyOf(ObjectPropertyChain(:p :q) :r) ObjectPropertyRange(:r :A) ObjectPropertyRange(:q :A) )");
    cases.put("chainRangeInherited", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubObjectPropertyOf(ObjectPropertyChain(:p :q) :r) SubObjectPropertyOf(:q :p) ObjectPropertyRange(:r :A) ObjectPropertyRange(:p :A) )");
    cases.put("undeclared", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) SubClassOf(<urn:profiles:undeclared> :A) )");
    cases.put("topObject", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) ObjectPropertyAssertion(owl:topObjectProperty :i :j) )");
    cases.put("bottomData", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) DataPropertyAssertion(owl:bottomDataProperty :i \"text\") )");
    cases.put("nonsimple", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) TransitiveObjectProperty(:p) FunctionalObjectProperty(:p) )");
    cases.put("datatype_decimal", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:decimal)) )");
    cases.put("datatype_integer", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:integer)) )");
    cases.put("datatype_nonNegativeInteger", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:nonNegativeInteger)) )");
    cases.put("datatype_string", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:string)) )");
    cases.put("datatype_normalizedString", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:normalizedString)) )");
    cases.put("datatype_token", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:token)) )");
    cases.put("datatype_Name", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:Name)) )");
    cases.put("datatype_NCName", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:NCName)) )");
    cases.put("datatype_NMTOKEN", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:NMTOKEN)) )");
    cases.put("datatype_hexBinary", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:hexBinary)) )");
    cases.put("datatype_base64Binary", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:base64Binary)) )");
    cases.put("datatype_anyURI", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:anyURI)) )");
    cases.put("datatype_dateTime", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:dateTime)) )");
    cases.put("datatype_dateTimeStamp", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:dateTimeStamp)) )");
    cases.put("datatype_double", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:double)) )");
    cases.put("datatype_float", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:float)) )");
    cases.put("datatype_nonPositiveInteger", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:nonPositiveInteger)) )");
    cases.put("datatype_positiveInteger", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:positiveInteger)) )");
    cases.put("datatype_negativeInteger", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:negativeInteger)) )");
    cases.put("datatype_long", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:long)) )");
    cases.put("datatype_int", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:int)) )");
    cases.put("datatype_short", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:short)) )");
    cases.put("datatype_byte", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:byte)) )");
    cases.put("datatype_unsignedLong", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:unsignedLong)) )");
    cases.put("datatype_unsignedInt", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:unsignedInt)) )");
    cases.put("datatype_unsignedShort", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:unsignedShort)) )");
    cases.put("datatype_unsignedByte", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:unsignedByte)) )");
    cases.put("datatype_language", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:language)) )");
    cases.put("datatype_boolean", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(xsd:boolean)) )");
    cases.put("datatype_owl_real", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(owl:real)) )");
    cases.put("datatype_owl_rational", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(owl:rational)) )");
    cases.put("datatype_rdf_PlainLiteral", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(rdf:PlainLiteral)) )");
    cases.put("datatype_rdf_XMLLiteral", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(rdf:XMLLiteral)) )");
    cases.put("datatype_rdfs_Literal", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(rdfs:Literal)) )");
    cases.put("datatype_rdf_langString", "Prefix(:=<urn:profiles:>) Prefix(owl:=<http://www.w3.org/2002/07/owl#>) Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>) Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>) Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>) Ontology( Declaration(Class(:A)) Declaration(Class(:B)) Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q)) Declaration(ObjectProperty(:r)) Declaration(DataProperty(:d)) Declaration(DataProperty(:e)) Declaration(NamedIndividual(:i)) Declaration(NamedIndividual(:j)) Declaration(Datatype(rdf:langString)) )");
    String base = cases.get("empty").replaceAll(" \\)$", " ");
    List<String> expressions = List.of(":A","owl:Thing","ObjectIntersectionOf(:A :B)","ObjectUnionOf(:A :B)","ObjectComplementOf(:A)","ObjectSomeValuesFrom(:p owl:Thing)","ObjectSomeValuesFrom(:p :A)","ObjectAllValuesFrom(:p :A)","ObjectHasValue(:p :i)","ObjectHasSelf(:p)","ObjectOneOf(:i :j)","ObjectMaxCardinality(0 :p :A)","ObjectMaxCardinality(1 :p ObjectUnionOf(:A :B))","DataSomeValuesFrom(:d xsd:string)","DataAllValuesFrom(:d xsd:string)","DataHasValue(:d \"text\")","DataMaxCardinality(1 :d xsd:string)");
    for (int index = 0; index < expressions.size(); index++) {
      String expression = expressions.get(index);
      for (String position : List.of("sub","super","equiv","disjoint","assertion","key")) {
        String axiom = switch(position) {
          case "sub" -> "SubClassOf(" + expression + " :B)";
          case "super" -> "SubClassOf(:B " + expression + ")";
          case "equiv" -> "EquivalentClasses(:B " + expression + ")";
          case "disjoint" -> "DisjointClasses(:B " + expression + ")";
          case "assertion" -> "ClassAssertion(" + expression + " :i)";
          default -> "HasKey(" + expression + " (:p) (:d))";
        };
        cases.put("position_" + position + "_" + index, base + axiom + " )");
      }
    }
    cases.put("annotationLanguageLiteral", "Ontology(AnnotationAssertion(<http://www.w3.org/2000/01/rdf-schema#label> <urn:profiles:A> \"Label\"@en))");
    cases.put("ontologyLanguageLiteral", "Ontology(Annotation(<http://www.w3.org/2000/01/rdf-schema#label> \"Label\"@en))");
    cases.put("dataLanguageLiteral", "Ontology(Declaration(DataProperty(<urn:profiles:d>)) Declaration(NamedIndividual(<urn:profiles:i>)) DataPropertyAssertion(<urn:profiles:d> <urn:profiles:i> \"Label\"@en))");
    cases.put("annotationBooleanLiteral", "Ontology(AnnotationAssertion(<http://www.w3.org/2000/01/rdf-schema#label> <urn:profiles:A> \"true\"^^<http://www.w3.org/2001/XMLSchema#boolean>))");
    cases.put("annotationCustomDatatype", "Ontology(AnnotationAssertion(<http://www.w3.org/2000/01/rdf-schema#label> <urn:profiles:A> \"Label\"^^<urn:profiles:custom>))");
    cases.put("annotationAnonymousValue", "Ontology(AnnotationAssertion(<http://www.w3.org/2000/01/rdf-schema#label> <urn:profiles:A> _:value))");
    // Common DL restrictions remain relevant even when the fragment grammar
    // independently rejects the same axiom. Probe both reports explicitly.
    String[][] common = {
      {"propertyCategory", "Declaration(DataProperty(:p))"},
      {"classDatatype", "Declaration(Datatype(:A)) DatatypeDefinition(:A xsd:string)"},
      {"reservedClass", "Declaration(Class(owl:topObjectProperty))"},
      {"reservedObjectProperty", "Declaration(ObjectProperty(owl:Thing))"},
      {"reservedIndividual", "Declaration(NamedIndividual(owl:Thing))"},
      {"reservedDatatype", "Declaration(Datatype(xsd:madeUp))"},
      {"badAnnotationLiteral", "AnnotationAssertion(rdfs:label :A \"256\"^^xsd:unsignedByte)"},
      {"badNestedAnnotationLiteral", "SubClassOf(Annotation(Annotation(rdfs:label \"bad\"^^xsd:integer) rdfs:label \"ok\") :A :B)"},
      {"definedLiteral", "Declaration(Datatype(:type)) DatatypeDefinition(:type xsd:string) AnnotationAssertion(rdfs:label :A \"text\"^^:type)"},
      {"definedRestriction", "Declaration(Datatype(:type)) DatatypeDefinition(:type xsd:string) DataPropertyRange(:d DatatypeRestriction(:type xsd:length \"1\"^^xsd:integer))"},
      {"badFacetValue", "DataPropertyRange(:d DatatypeRestriction(xsd:byte xsd:minInclusive \"300\"^^xsd:integer))"},
      {"multipleDefinitions", "Declaration(Datatype(:type)) DatatypeDefinition(:type xsd:string) DatatypeDefinition(:type xsd:integer)"},
      {"redefinedBuiltin", "DatatypeDefinition(xsd:string xsd:integer)"},
      {"cyclicDefinitions", "Declaration(Datatype(:x)) Declaration(Datatype(:y)) DatatypeDefinition(:x DataUnionOf(xsd:string :y)) DatatypeDefinition(:y :x)"},
      {"topDataDeclaration", "Declaration(DataProperty(owl:topDataProperty))"},
      {"naryDataRange", "SubClassOf(:A DataSomeValuesFrom(:d :e xsd:string))"},
      {"anonymousSame", "SameIndividual(_:a :i)"},
      {"anonymousDifferent", "DifferentIndividuals(_:a :i)"},
      {"anonymousNegativeObject", "NegativeObjectPropertyAssertion(:p _:a :i)"},
      {"anonymousNegativeData", "NegativeDataPropertyAssertion(:d _:a \"text\")"},
      {"anonymousNominal", "SubClassOf(:A ObjectOneOf(_:a))"},
      {"anonymousHasValue", "SubClassOf(:A ObjectHasValue(:p _:a))"},
      {"anonymousCycle", "ObjectPropertyAssertion(:p _:a _:b) ObjectPropertyAssertion(:p _:b _:c) ObjectPropertyAssertion(:p _:c _:a)"},
      {"anonymousDuplicateEdge", "ObjectPropertyAssertion(:p _:a _:b) ObjectPropertyAssertion(:q _:a _:b)"},
      {"anonymousNoRoot", "ObjectPropertyAssertion(:p _:a :i) ObjectPropertyAssertion(:p _:a :j)"},
      {"legalPropertyCycle", "SubObjectPropertyOf(:p :q) SubObjectPropertyOf(:q :p)"},
      {"legalRecursiveChain", "SubObjectPropertyOf(ObjectPropertyChain(:p :p) :p)"},
      {"irregularMiddleHead", "SubObjectPropertyOf(ObjectPropertyChain(:p :q :p) :p)"},
      {"irregularHierarchy", "SubObjectPropertyOf(ObjectPropertyChain(:p :q) :r) SubObjectPropertyOf(:r :p)"},
      {"legalPunning", "Declaration(NamedIndividual(:A)) ClassAssertion(:A :A)"},
      {"legalAnnotationLiteral", "AnnotationAssertion(rdfs:label :A \"255\"^^xsd:unsignedByte)"},
      {"legalAnonymousTree", "ObjectPropertyAssertion(:p _:a _:b) ObjectPropertyAssertion(:p _:b :i)"}
    };
    for (String[] vector : common) cases.put("common_" + vector[0], base + vector[1] + " )");
    String[][] simple = {
      {"min", "SubClassOf(:B ObjectMinCardinality(1 :q :A))"},
      {"maxInverse", "SubClassOf(:B ObjectMaxCardinality(1 ObjectInverseOf(:q) :A))"},
      {"exact", "SubClassOf(:B ObjectExactCardinality(1 :q :A))"},
      {"self", "SubClassOf(:B ObjectHasSelf(:q))"},
      {"functional", "FunctionalObjectProperty(:q)"},
      {"inverseFunctional", "InverseFunctionalObjectProperty(:q)"},
      {"irreflexive", "IrreflexiveObjectProperty(:q)"},
      {"asymmetric", "AsymmetricObjectProperty(:q)"},
      {"disjoint", "DisjointObjectProperties(:q :r)"}
    };
    for (String[] vector : simple) cases.put("common_nonsimple_" + vector[0], base + "TransitiveObjectProperty(:p) SubObjectPropertyOf(:p :q) " + vector[1] + " )");
    List<Map<String,Object>> output = new ArrayList<>();
    for (var entry : cases.entrySet()) {
      // Use complete built-in IRIs: the JavaScript parser reserves these
      // prefix names rather than accepting redundant declarations.
      String input = entry.getValue();
      for (var prefix : Map.of("owl","http://www.w3.org/2002/07/owl#","rdf","http://www.w3.org/1999/02/22-rdf-syntax-ns#","rdfs","http://www.w3.org/2000/01/rdf-schema#","xsd","http://www.w3.org/2001/XMLSchema#").entrySet()) {
        input = input.replace("Prefix(" + prefix.getKey() + ":=<" + prefix.getValue() + ">) ", "");
        input = input.replaceAll("\\b" + prefix.getKey() + ":([A-Za-z][A-Za-z0-9]*)", "<" + prefix.getValue() + "$1>");
      }
      var manager = OWLManager.createOWLOntologyManager();
      var ontology = manager.loadOntologyFromOntologyDocument(new StringDocumentSource(input));
      Map<String,Object> row = new LinkedHashMap<>();
      row.put("id",entry.getKey()); row.put("input",input);
      Map<String,Object> profiles = new LinkedHashMap<>();
      for (OWLProfile profile : List.of(new OWL2DLProfile(),new OWL2ELProfile(),new OWL2QLProfile(),new OWL2RLProfile())) {
        Map<String,Object> result = new LinkedHashMap<>();
        try {
          var report = profile.checkOntology(ontology);
          result.put("inProfile", report.isInProfile());
          result.put("violations", report.getViolations().stream().map(v -> v.getClass().getSimpleName()).sorted().toList());
        } catch (RuntimeException exception) {
          result.put("error", exception.getClass().getSimpleName());
          result.put("message", exception.getMessage());
        }
        profiles.put(profile.getName(),result);
      }
      row.put("profiles",profiles); output.add(row);
    }
    ObjectMapper mapper = new ObjectMapper(); mapper.getFactory().configure(JsonGenerator.Feature.ESCAPE_NON_ASCII,true);
    Map<String,Object> fixture = new LinkedHashMap<>();
    fixture.put("schemaVersion",1);
    fixture.put("sourceRevision","b61ebe2da83daceebb3e7ba7afbd2582c9240c33");
    fixture.put("runtimeQualification","EXISTING_RUNTIME_OBSERVATION_REQUIRES_FRESH_BUILD_BINDING");
    fixture.put("harness","util/owlapi-reference/RunRC2Profiles.java");
    fixture.put("specification","https://www.w3.org/TR/owl2-profiles/");
    fixture.put("observations",output);
    String json = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(fixture) + "\n";
    if (arguments.length > 0) Files.writeString(Path.of(arguments[0]), json);
    else System.out.println(json);
  }
}
