import { OWLManager } from "../apibinding/index.js";
import { RDFXMLDocumentFormat, OWLDocumentFormats } from "./index.js";
import { StringDocumentSource, StringDocumentTarget } from "../io/index.js";
import { OWLOntologyWriterConfiguration } from "../model/index.js";
import { compareOntologies } from "../internal/model/ontologyStructuralIsomorphism.js";

const source = `<?xml version="1.0"?>
<rdf:RDF xmlns="urn:example:" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:schema="http://schema.org/" xmlns:unused="urn:unused:">
 <owl:Ontology rdf:about="urn:example:ontology"/>
 <owl:Class rdf:about="urn:example:C"><schema:name>quote &quot; and &apos;\r&#xD;tail</schema:name></owl:Class>
 <owl:AnnotationProperty rdf:about="http://schema.org/name"/>
</rdf:RDF>`;
const load = (manager, text = source) =>
  manager.loadOntologyFromOntologyDocument(new StringDocumentSource(text));
const save = async (manager, ontology, format = OWLDocumentFormats.RDF_XML) => {
  const target = new StringDocumentTarget();
  await manager.saveOntology(ontology, format, target);
  return target.toString();
};

describe("Java-backed RDF/XML prefix and presentation refinement", () => {
  it("treats a cleared source default namespace as absent without discarding valid named preferences", async () => {
    const manager = OWLManager.createOWLOntologyManager();
    const ontology = await load(
      manager,
      source.replace(
        'xmlns="urn:example:"',
        'xmlns="" xmlns:xmlschema="urn:xmlschema:"',
      ),
    );
    const format = manager.getOntologyFormat(ontology);
    expect(format.getDefaultPrefix()).toBeNull();
    expect(format.getPrefix("xmlschema:")).toBe("urn:xmlschema:");
    const output = await save(manager, ontology, format);
    expect(output).toContain('xmlns:xmlschema="urn:xmlschema:"');
    expect(
      compareOntologies(
        ontology,
        await load(OWLManager.createOWLOntologyManager(), output),
      ).equal,
    ).toBe(true);
  });

  it("preserves every explicit alias when inferring another namespace prefix", async () => {
    const manager = OWLManager.createOWLOntologyManager();
    const ontology = await load(
      manager,
      'Ontology(<urn:alias:ontology> Declaration(Class(<urn:alias:C>)) Declaration(AnnotationProperty(<http://other.example/alias#property>)) AnnotationAssertion(<http://other.example/alias#property> <urn:alias:C> "value"))',
    );
    const format = new RDFXMLDocumentFormat();
    format.setDefaultPrefix("urn:example:");
    format.setPrefix("alias:", "urn:example:");
    format.setPrefix("otherAlias:", "urn:example:");
    const output = await save(manager, ontology, format);
    expect(output).toContain('xmlns:alias="urn:example:"');
    expect(output).toContain('xmlns:otherAlias="urn:example:"');
    expect(
      compareOntologies(
        ontology,
        await load(OWLManager.createOWLOntologyManager(), output),
      ).equal,
    ).toBe(true);
  });

  it("retains root prefixes separately from immutable parse metadata and copies them through the public format", async () => {
    const manager = OWLManager.createOWLOntologyManager();
    const ontology = await load(manager);
    const loaded = manager.getOntologyFormat(ontology);
    expect(loaded).toBeInstanceOf(RDFXMLDocumentFormat);
    expect(loaded.isPrefixOWLDocumentFormat()).toBe(true);
    expect(loaded.asPrefixOWLDocumentFormat()).toBe(loaded);
    expect(loaded.getDefaultPrefix()).toBe("urn:example:");
    const metadata = loaded.getOntologyLoaderMetaData();
    const prefixes = loaded.getPrefixName2PrefixMap();
    prefixes.delete("schema:");
    expect(loaded.getPrefix("schema:")).toBe("http://schema.org/");
    const format = new RDFXMLDocumentFormat();
    format.copyPrefixesFrom(loaded);
    const text = await save(manager, ontology, format);
    expect(text).toContain(
      '<rdf:RDF xmlns="urn:example:"\n     xml:base="urn:example:"',
    );
    expect(text).toContain('xmlns:unused="urn:unused:"');
    expect(text).toContain(
      "<schema:name>quote &quot; and &apos;\n&#xD;tail</schema:name>",
    );
    expect(text).toContain("// Classes");
    expect(text).toMatch(/<!-- urn:example:C -->\n\n\n {4}<owl:Class/u);
    expect(text).not.toContain("#Ontology -->");
    expect(text).toContain(
      "Generated by @hadden-industries/owlapi (JavaScript implementation; version 0.1.0-rc.1)",
    );
    expect(text).not.toContain("Generated by the OWL API");
    expect(
      compareOntologies(
        ontology,
        await load(OWLManager.createOWLOntologyManager(), text),
      ).equal,
    ).toBe(true);
    loaded.setPrefix("schema:", "urn:changed:");
    expect(loaded.getOntologyLoaderMetaData()).toBe(metadata);
    expect(manager.getOntologyFormat(ontology)).toBe(loaded);
  });

  it("captures mutable prefix choices before suspension and preserves them in immutable parameter copies", async () => {
    const manager = OWLManager.createOWLOntologyManager();
    const ontology = await load(manager);
    const base = new RDFXMLDocumentFormat();
    base.copyPrefixesFrom(manager.getOntologyFormat(ontology));
    const format = base.withParameter("force xsd:string on literals", true);
    expect(format).toBeInstanceOf(RDFXMLDocumentFormat);
    const target = new StringDocumentTarget();
    const saving = manager.saveOntology(ontology, format, target);
    format.setPrefix("schema:", "urn:changed:");
    await saving;
    expect(target.toString()).toContain(
      '<schema:name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">',
    );
    expect(target.toString()).toContain('xmlns:schema="http://schema.org/"');
    expect(base.getParameter("force xsd:string on literals", false)).toBe(
      false,
    );
    expect(base.getPrefix("schema:")).toBe("http://schema.org/");
  });

  it("validates complete prefix copies atomically and supports inherited Java collection operations", () => {
    const format = new RDFXMLDocumentFormat();
    const before = format.getPrefixName2PrefixMap();
    expect(() =>
      format.copyPrefixesFrom(
        new Map([
          ["ok:", "urn:ok:"],
          ["bad:colon:", "urn:bad:"],
        ]),
      ),
    ).toThrow();
    expect(format.getPrefixName2PrefixMap()).toEqual(before);
    expect(() => format.setPrefix("xml:", "urn:wrong:")).toThrow();
    expect(() => format.setPrefix("xmlns:", "urn:wrong:")).toThrow();
    expect(() => format.setPrefix("x:", "urn:x:\u0000")).toThrow();
    format.setDefaultPrefix("urn:default:");
    expect(format.getPrefix(":")).toBe("urn:default:");
    format.setDefaultPrefix(null);
    expect(format.getDefaultPrefix()).toBeNull();
    format.setPrefix("a:", "urn:a:");
    expect(format.getPrefixNames().has("a:")).toBe(true);
    format.unregisterNamespace("urn:a:");
    expect(format.containsPrefixMapping("a:")).toBe(false);
    format.clear();
    expect(format.getPrefixName2PrefixMap().size).toBe(0);
    expect(() => new RDFXMLDocumentFormat({})).toThrow(TypeError);
  });

  it("preserves graphs when preferred aliases collide with RDF syntax names", async () => {
    const manager = OWLManager.createOWLOntologyManager();
    const ontology = await load(manager);
    const format = new RDFXMLDocumentFormat();
    format.setPrefix("rdf:", "urn:application:");
    format.setPrefix("r:", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
    const text = await save(manager, ontology, format);
    expect(text).toContain("<r:RDF ");
    expect(text).toContain('r:about="urn:example:C"');
    expect(text).not.toContain("rdf:about=");
    expect(
      compareOntologies(
        ontology,
        await load(OWLManager.createOWLOntologyManager(), text),
      ).equal,
    ).toBe(true);
  });

  it("allocates a nonempty RDF syntax attribute prefix when RDF is the default namespace", async () => {
    const manager = OWLManager.createOWLOntologyManager();
    const ontology = await load(manager);
    const format = new RDFXMLDocumentFormat();
    format.clear();
    format.setDefaultPrefix("http://www.w3.org/1999/02/22-rdf-syntax-ns#");
    const output = await save(manager, ontology, format);
    expect(output).toContain(
      'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"',
    );
    expect(output).toContain('rdf:about="urn:example:C"');
    expect(
      compareOntologies(
        ontology,
        await load(OWLManager.createOWLOntologyManager(), output),
      ).equal,
    ).toBe(true);
  });

  it("keeps annotated axioms adjacent, omits dispensable IDs, and supports Java's explicit ID setting", async () => {
    const manager = OWLManager.createOWLOntologyManager();
    const ontology = await load(
      manager,
      `Ontology(<urn:ids:ontology>
      Declaration(Class(<urn:ids:A>)) Declaration(Class(<urn:ids:Z>))
      Declaration(AnnotationProperty(<urn:note:label>)) Declaration(ObjectProperty(<urn:ids:p>))
      SubClassOf(Annotation(<urn:note:label> "annotation") <urn:ids:A> <urn:ids:Z>)
      ClassAssertion(<urn:ids:A> _:individual)
      SubClassOf(<urn:ids:Z> ObjectSomeValuesFrom(<urn:ids:p> <urn:ids:A>))
    )`,
    );
    const text = await save(manager, ontology);
    expect(text.indexOf("<owl:Axiom")).toBeGreaterThan(
      text.indexOf('<owl:Class rdf:about="urn:ids:A"'),
    );
    expect(text.indexOf("<owl:Axiom")).toBeLessThan(
      text.indexOf('<owl:Class rdf:about="urn:ids:Z"'),
    );
    expect(text).not.toContain("rdf:nodeID");
    const defaults = new OWLOntologyWriterConfiguration();
    expect(defaults.shouldSaveIdsForAllAnonymousIndividuals()).toBe(false);
    manager.setOntologyWriterConfiguration(
      defaults.withSaveIdsForAllAnonymousIndividuals(true),
    );
    const identified = await save(manager, ontology);
    expect(identified).toMatch(/<owl:Axiom rdf:nodeID=/u);
    expect(identified).not.toMatch(/<owl:Restriction rdf:nodeID=/u);
    expect(
      compareOntologies(
        ontology,
        await load(OWLManager.createOWLOntologyManager(), identified),
      ).equal,
    ).toBe(true);
    expect(defaults.shouldSaveIdsForAllAnonymousIndividuals()).toBe(false);
    expect(() =>
      defaults.withSaveIdsForAllAnonymousIndividuals("true"),
    ).toThrow(TypeError);
  });
});
